# -*- coding: utf-8 -*-
"""Ключ карточки -> номер её картинки в static/words.svg.

Файл СОБИРАЕТСЯ автоматически: tools/build_words_art.py.
Править руками бессмысленно — перезапишется при первой же
пересборке спрайта. Рисунки лежат в tools/art_w_*.py.
"""

ART = {
    "adjectives:טוב": "i0",
    "adjectives:רע": "i1",
    "adjectives:יפה": "i2",
    "adjectives:חדש": "i3",
    "adjectives:ישן": "i4",
    "adjectives:גדול": "i5",
    "adjectives:קטן": "i6",
    "adjectives:עתיק": "i7",
    "adjectives:מיוחד": "i8",
    "adjectives:מענין": "i9",
    "adverbs:הרבה": "i10",
    "adverbs:בשקט": "i11",
    "adverbs:מהר": "i12",
    "adverbs:לאט": "i13",
    "adverbs:קשה": "i14",
    "question_words:מה": "i15",
    "question_words:מי": "i16",
    "question_words:איפה": "i17",
    "question_words:לאן": "i18",
    "question_words:מאין": "i19",
    "question_words:איזה": "i20",
    "question_words:איזו": "i21",
    "question_words:אילו": "i22",
    "question_words:מתי": "i23",
    "question_words:למה": "i24",
    "particles:יש": "i25",
    "particles:אין": "i26",
    "particles:כל": "i27",
    "particles:אבל": "i28",
    "particles:משהו": "i29",
    "particles:מישהו": "i30",
    "cardinals:אחד": "i31",
    "cardinals:שנים": "i32",
    "cardinals:שלושה": "i33",
    "cardinals:ארבעה": "i34",
    "cardinals:חמשה": "i35",
    "cardinals:עשרה": "i36",
    "cardinals:עשרים": "i37",
    "cardinals:מאה": "i38",
    "cardinals:אלף": "i39",
    "ordinals:ראשון": "i40",
    "ordinals:שני": "i41",
    "ordinals:שלישי": "i42",
    "ordinals:חמישי": "i43",
    "ordinals:עשירי": "i44",
    "object_pronouns:אותי": "i45",
    "object_pronouns:אותו": "i46",
    "object_pronouns:אותה": "i47",
    "object_pronouns:אותנו": "i48",
    "object_pronouns:אתכם": "i49",
    "object_pronouns:אותם": "i50",
    "personal_pronouns:אני": "i51",
    "personal_pronouns:אתה": "i52",
    "personal_pronouns:את": "i53",
    "personal_pronouns:הוא": "i54",
    "personal_pronouns:היא": "i55",
    "personal_pronouns:אנחנו": "i56",
    "personal_pronouns:אתם": "i57",
    "personal_pronouns:אתן": "i58",
    "personal_pronouns:הם": "i59",
    "personal_pronouns:הן": "i60",
    "greetings:שלום": "i61",
    "greetings:בקר טוב": "i62",
    "greetings:ערב טוב": "i63",
    "greetings:לילה טוב": "i64",
    "greetings:תודה": "i65",
    "greetings:בבקשה": "i66",
    "greetings:סליחה": "i67",
    "greetings:להתראות": "i68",
    "greetings:נעים מאד": "i69",
    "greetings:כן": "i70",
    "greetings:לא": "i71",
    "greetings:אולי": "i72",
    "family:אמא": "i73",
    "family:אבא": "i74",
    "family:בן": "i75",
    "family:בת": "i76",
    "family:אח": "i77",
    "family:אחות": "i78",
    "family:בעל": "i79",
    "family:אשה": "i80",
    "family:גבר": "i81",
    "family:ילד": "i82",
    "family:ילדה": "i83",
    "family:סבא": "i84",
    "family:סבתא": "i85",
    "family:הורים": "i86",
    "family:משפחה": "i87",
    "family:חבר": "i88",
    "family:חברה": "i89",
    "family:שם": "i90",
    "food:לחם": "i91",
    "food:מים": "i92",
    "food:חלב": "i93",
    "food:גבינה": "i94",
    "food:ביצה": "i95",
    "food:בשר": "i96",
    "food:עוף": "i97",
    "food:דג": "i98",
    "food:אורז": "i99",
    "food:מרק": "i100",
    "food:סלט": "i101",
    "food:ירקות": "i102",
    "food:פרות": "i103",
    "food:תפוח": "i104",
    "food:תפוז": "i105",
    "food:עגבניה": "i106",
    "food:מלפפון": "i107",
    "food:חמאה": "i108",
    "food:סכר": "i109",
    "food:מלח": "i110",
    "food:קפה": "i111",
    "food:תה": "i112",
    "food:יין": "i113",
    "food:ארוחת בקר": "i114",
    "food:ארוחת צהרים": "i115",
    "food:ארוחת ערב": "i116",
    "home:בית": "i117",
    "home:דירה": "i118",
    "home:חדר": "i119",
    "home:מטבח": "i120",
    "home:שרותים": "i121",
    "home:סלון": "i122",
    "home:חדר שנה": "i123",
    "home:שלחן": "i124",
    "home:כסא": "i125",
    "home:מטה": "i126",
    "home:דלת": "i127",
    "home:חלון": "i128",
    "home:ארון": "i129",
    "home:מקרר": "i130",
    "home:מפתח": "i131",
    "home:רצפה": "i132",
    "home:מרפסת": "i133",
    "home:מדרגות": "i134",
    "city:עיר": "i135",
    "city:רחוב": "i136",
    "city:ככר": "i137",
    "city:חנות": "i138",
    "city:שוק": "i139",
    "city:בנק": "i140",
    "city:דאר": "i141",
    "city:בית מרקחת": "i142",
    "city:בית חולים": "i143",
    "city:בית ספר": "i144",
    "city:אוניברסיטה": "i145",
    "city:מסעדה": "i146",
    "city:בית קפה": "i147",
    "city:פארק": "i148",
    "city:חוף": "i149",
    "city:בית כנסת": "i150",
    "city:מלון": "i151",
    "city:סופרמרקט": "i152",
    "transport:מכונית": "i153",
    "transport:אוטובוס": "i154",
    "transport:רכבת": "i155",
    "transport:מטוס": "i156",
    "transport:מונית": "i157",
    "transport:אופנים": "i158",
    "transport:תחנה": "i159",
    "transport:כרטיס": "i160",
    "transport:דרך": "i161",
    "transport:רמזור": "i162",
    "transport:פקק": "i163",
    "transport:נמל תעופה": "i164",
    "time:יום": "i165",
    "time:לילה": "i166",
    "time:בקר": "i167",
    "time:ערב": "i168",
    "time:צהרים": "i169",
    "time:שבוע": "i170",
    "time:חדש": "i171",
    "time:שנה": "i172",
    "time:שעה": "i173",
    "time:דקה": "i174",
    "time:היום": "i175",
    "time:אתמול": "i176",
    "time:מחר": "i177",
    "time:עכשיו": "i178",
    "time:אחר כך": "i179",
    "time:תמיד": "i180",
    "time:אף פעם": "i181",
    "time:לפעמים": "i182",
    "time:יום ראשון": "i183",
    "time:יום שני": "i184",
    "time:שבת": "i185",
    "weather:מזג אויר": "i186",
    "weather:שמש": "i187",
    "weather:גשם": "i188",
    "weather:רוח": "i189",
    "weather:ענן": "i190",
    "weather:חם": "i191",
    "weather:קר": "i192",
    "weather:שלג": "i193",
    "weather:שמים": "i194",
    "weather:ים": "i195",
    "health:רופא": "i196",
    "health:חולה": "i197",
    "health:בריא": "i198",
    "health:כאב": "i199",
    "health:ראש": "i200",
    "health:יד": "i201",
    "health:רגל": "i202",
    "health:עין": "i203",
    "health:אזן": "i204",
    "health:פה": "i205",
    "health:אף": "i206",
    "health:שן": "i207",
    "health:בטן": "i208",
    "health:גב": "i209",
    "health:לב": "i210",
    "health:תרופה": "i211",
    "health:קפת חולים": "i212",
    "shopping:כסף": "i213",
    "shopping:מחיר": "i214",
    "shopping:יקר": "i215",
    "shopping:זול": "i216",
    "shopping:הנחה": "i217",
    "shopping:חשבון": "i218",
    "shopping:קפה": "i219",
    "shopping:כרטיס אשראי": "i220",
    "shopping:עדף": "i221",
    "shopping:שקל": "i222",
    "shopping:מוכר": "i223",
    "shopping:לקוח": "i224",
    "shopping:תיק": "i225",
    "shopping:שקית": "i226",
    "work_study:עבודה": "i227",
    "work_study:משרד": "i228",
    "work_study:מנהל": "i229",
    "work_study:משכרת": "i230",
    "work_study:שעור": "i231",
    "work_study:מורה": "i232",
    "work_study:תלמיד": "i233",
    "work_study:סטודנט": "i234",
    "work_study:ספר": "i235",
    "work_study:מחברת": "i236",
    "work_study:עט": "i237",
    "work_study:שאלה": "i238",
    "work_study:תשובה": "i239",
    "work_study:מבחן": "i240",
    "clothes:בגדים": "i241",
    "clothes:חלצה": "i242",
    "clothes:מכנסים": "i243",
    "clothes:שמלה": "i244",
    "clothes:חצאית": "i245",
    "clothes:נעלים": "i246",
    "clothes:מעיל": "i247",
    "clothes:כובע": "i248",
    "clothes:גרבים": "i249",
    "clothes:משקפים": "i250",
    "emotions:שמחה": "i251",
    "emotions:עצב": "i252",
    "emotions:אהבה": "i253",
    "emotions:פחד": "i254",
    "emotions:מאשר": "i255",
    "emotions:כועס": "i256",
    "emotions:רעב": "i257",
    "emotions:צמא": "i258",
    "emotions:עיף": "i259",
    "emotions:מרצה": "i260",
    "emotions:רגוע": "i261",
    "place_prepositions:על": "i262",
    "place_prepositions:מתחת": "i263",
    "place_prepositions:מעל": "i264",
    "place_prepositions:ליד": "i265",
    "place_prepositions:בין": "i266",
    "place_prepositions:בתוך": "i267",
    "place_prepositions:בחוץ": "i268",
    "place_prepositions:לפני": "i269",
    "place_prepositions:אחרי": "i270",
    "place_prepositions:כאן": "i271",
    "place_prepositions:שם": "i272"
}
